name = "nine9s-webhook-discord"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""


[build]
command = "yarn && yarn build"
[build.upload]
format = "service-worker"

# [secrets]
# NINE9S_WEBHOOK_SECRET
# DISCORD_WEBHOOK_URL
